name: Medium Yazıları Güncelleme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Depo Kontrol Et
        uses: actions/checkout@v2 # Depo kontrol etme adımı
      - name: Medium RSS Beslemesini Al
        run: |
          curl -s "https://medium.com/feed/@murathankaragooz" |
          awk -F '<title>|</title>' '/<title>/{print $2}' |
          sed '1d' |
          head -n 5 > medium_yazilari.txt
      - name: README Dosyasını Güncelle ve GitHub Pages'e Yayınla
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./
          commit_message: "Medium yazıları güncellendi"
          publish_branch: gh-pages
      - name: README Dosyasını Ana Branch'e Geri Yükle
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "readme güncellendi"
          file_pattern: README.md
          repository: . # Geçerli dizini belirt
